#xuecheng:
#  fastdfs:
#    connect_timeout_in_seconds: 5000
#    network_timeout_in_seconds: 30000
#    charset: UTF-8
#    tracker_servers: 192.168.25.133:22122 #多个 trackerServer中间以逗号分隔
#  此处配置已废弃，改为直接在类中注入